# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vMMv_arma <- function(x, A, B, y) {
    .Call(`_spacelink_vMMv_arma`, x, A, B, y)
}

vMv_arma <- function(x, A, y) {
    .Call(`_spacelink_vMv_arma`, x, A, y)
}

invM_arma <- function(mat) {
    .Call(`_spacelink_invM_arma`, mat)
}

